services:
    bank-microservices-database:
        image: postgres:alpine
        container_name: bank-microservices-database
        volumes:
            - bank-microservices-database-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - bank-microservices-network

    costumers-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: costumers-microservice
        depends_on:
            - bank-microservices-database
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - bank-microservices-network

networks:
    bank-microservices-network:
        driver: bridge
        external: true

volumes:
    bank-microservices-database-data:
