services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - bank-microservices-network

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./redis:/data
        networks:
            - bank-microservices-network

    redisadmin:
        image: erikdubbelboer/phpredisadmin:latest
        depends_on:
            - redis
        ports:
            - 8000:80
        environment:
            REDIS_1_HOST: redis
        networks:
            - bank-microservices-network

    bank-microservices-database:
        image: postgres:alpine
        container_name: bank-microservices-database
        volumes:
            - bank-microservices-database-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - bank-microservices-network

    costumers-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: costumers-microservice
        depends_on:
            - bank-microservices-database
            - redis
            - rabbitmq
        environment:
            - SERVER_PORT=3000
            - SECURITY_ENABLED=true
            - JWT_SECRET=thisismysecretjwt

            - DB_HOST=bank-microservices-database
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=dhhfn874_pdo|js__sundmdKJ7668
            - DB_NAME=bank-microservices-database
            - DB_SYNCRONIZE=true

            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - STORAGE_MICROSERVICE_URL=storage-microservice:8080/storage
            - RABBIT_MQ_URL=amqp://rabbitmq:5672
        ports:
            - 3000:3000
        networks:
            - bank-microservices-network

networks:
    bank-microservices-network:
        driver: bridge
        external: true

volumes:
    bank-microservices-database-data:
