services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - bank-microservices-network

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./redis:/data
        networks:
            - bank-microservices-network

    redisadmin:
        image: erikdubbelboer/phpredisadmin:latest
        ports:
            - 8000:80
        environment:
            REDIS_1_HOST: redis
        networks:
            - bank-microservices-network

    bank-microservices-database:
        image: postgres:alpine
        container_name: bank-microservices-database
        volumes:
            - bank-microservices-database-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - 5432:5432
        networks:
            - bank-microservices-network

    costumers-microservice:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: costumers-microservice
        depends_on:
            - bank-microservices-database
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - bank-microservices-network

networks:
    bank-microservices-network:
        driver: bridge
        external: true

volumes:
    bank-microservices-database-data:
